// Datos mock para desarrollo del frontend
// Despues se reemplazaran con datos reales de la BD

export const mockCategorias = [
  {
    id: 1,
    nombre: 'Cockteleria / Trago preparado',
    precioCliente: 30000,
    precioChica: 35000,
    comisionChica: 12000,
    activa: true,
  },
  {
    id: 2,
    nombre: 'Vodka naranja',
    precioCliente: 20000,
    precioChica: 25000,
    comisionChica: 10000,
    activa: true,
  },
  {
    id: 3,
    nombre: 'Botella Premium',
    precioCliente: 150000,
    precioChica: 160000,
    comisionChica: 48000,
    activa: true,
  },
  {
    id: 4,
    nombre: 'Botella Super Premium',
    precioCliente: 250000,
    precioChica: 270000,
    comisionChica: 81000,
    activa: true,
  },
]

export const mockChicas = [
  { id: 1, nombre: 'Ana', activa: true, fechaIngreso: '2025-01-15' },
  { id: 2, nombre: 'Maria', activa: true, fechaIngreso: '2025-02-01' },
  { id: 3, nombre: 'Sofia', activa: true, fechaIngreso: '2025-02-10' },
  { id: 4, nombre: 'Valentina', activa: true, fechaIngreso: '2025-02-20' },
  { id: 5, nombre: 'Lucia', activa: true, fechaIngreso: '2025-02-25' },
]

export const mockComandas = [
  {
    id: 1,
    fecha: new Date().toISOString(),
    hora: '23:45',
    categoria: mockCategorias[0],
    tipoConsumo: 'chica',
    chica1: mockChicas[0],
    chica2: undefined,
    precioBase: 35000,
    precioFinal: 35000,
    comisionTotal: 12000,
    comisionChica1: 12000,
    comisionChica2: undefined,
    medioPago: 'efectivo',
    estado: 'activa',
    usuario: { nombre: 'Admin' },
  },
  {
    id: 2,
    fecha: new Date().toISOString(),
    hora: '23:50',
    categoria: mockCategorias[2],
    tipoConsumo: 'chica',
    chica1: mockChicas[1],
    chica2: mockChicas[2],
    precioBase: 150000,
    precioFinal: 150000,
    comisionTotal: 45000,
    comisionChica1: 22500,
    comisionChica2: 22500,
    medioPago: 'transferencia',
    estado: 'activa',
    usuario: { nombre: 'Admin' },
  },
  {
    id: 3,
    fecha: new Date().toISOString(),
    hora: '00:15',
    categoria: mockCategorias[1],
    tipoConsumo: 'cliente',
    chica1: undefined,
    chica2: undefined,
    precioBase: 20000,
    precioFinal: 20000,
    comisionTotal: 0,
    comisionChica1: undefined,
    comisionChica2: undefined,
    medioPago: 'efectivo',
    estado: 'activa',
    usuario: { nombre: 'Admin' },
  },
  {
    id: 4,
    fecha: new Date(Date.now() - 86400000).toISOString(),
    hora: '22:30',
    categoria: mockCategorias[3],
    tipoConsumo: 'chica',
    chica1: mockChicas[3],
    chica2: undefined,
    precioBase: 270000,
    precioFinal: 270000,
    comisionTotal: 81000,
    comisionChica1: 81000,
    comisionChica2: undefined,
    medioPago: 'debito',
    estado: 'activa',
    usuario: { nombre: 'Admin' },
  },
]